delete from Access where true;

insert into Access (GraderID, PermissionID, SectionID) values (1, 15, 30);
insert into Access (GraderID, PermissionID, SectionID) values (2, 30, 29);
insert into Access (GraderID, PermissionID, SectionID) values (3, 14, 28);
insert into Access (GraderID, PermissionID, SectionID) values (4, 29, 27);
insert into Access (GraderID, PermissionID, SectionID) values (5, 13, 26);
insert into Access (GraderID, PermissionID, SectionID) values (6, 28, 25);
insert into Access (GraderID, PermissionID, SectionID) values (7, 12, 24);
insert into Access (GraderID, PermissionID, SectionID) values (8, 27, 23);
insert into Access (GraderID, PermissionID, SectionID) values (9, 11, 22);
insert into Access (GraderID, PermissionID, SectionID) values (10, 26, 21);
insert into Access (GraderID, PermissionID, SectionID) values (11, 10, 20);
insert into Access (GraderID, PermissionID, SectionID) values (12, 25, 19);
insert into Access (GraderID, PermissionID, SectionID) values (13, 9, 18);
insert into Access (GraderID, PermissionID, SectionID) values (14, 24, 17);
insert into Access (GraderID, PermissionID, SectionID) values (15, 8, 16);
insert into Access (GraderID, PermissionID, SectionID) values (16, 23, 15);
insert into Access (GraderID, PermissionID, SectionID) values (17, 7, 14);
insert into Access (GraderID, PermissionID, SectionID) values (18, 22, 13);
insert into Access (GraderID, PermissionID, SectionID) values (19, 6, 12);
insert into Access (GraderID, PermissionID, SectionID) values (20, 21, 11);
insert into Access (GraderID, PermissionID, SectionID) values (21, 5, 10);
insert into Access (GraderID, PermissionID, SectionID) values (22, 20, 9);
insert into Access (GraderID, PermissionID, SectionID) values (23, 4, 8);
insert into Access (GraderID, PermissionID, SectionID) values (24, 19, 7);
insert into Access (GraderID, PermissionID, SectionID) values (25, 3, 6);
insert into Access (GraderID, PermissionID, SectionID) values (26, 18, 5);
insert into Access (GraderID, PermissionID, SectionID) values (27, 2, 4);
insert into Access (GraderID, PermissionID, SectionID) values (28, 17, 3);
insert into Access (GraderID, PermissionID, SectionID) values (29, 1, 2);
insert into Access (GraderID, PermissionID, SectionID) values (30, 16, 1);

commit;
