delete from Criteria where true;

insert into Criteria (ID, LabID, Name, MaxScore) values (1, 29, 'implementation', 1);
insert into Criteria (ID, LabID, Name, MaxScore) values (2, 23, 'homogeneous', 5);
insert into Criteria (ID, LabID, Name, MaxScore) values (3, 17, 'moderator', 98);
insert into Criteria (ID, LabID, Name, MaxScore) values (4, 7, 'toolset', 64);
insert into Criteria (ID, LabID, Name, MaxScore) values (5, 1, '3rd generation', 6);
insert into Criteria (ID, LabID, Name, MaxScore) values (6, 2, '4th generation', 6);
insert into Criteria (ID, LabID, Name, MaxScore) values (7, 27, 'modular', 58);
insert into Criteria (ID, LabID, Name, MaxScore) values (8, 18, 'analyzer', 46);
insert into Criteria (ID, LabID, Name, MaxScore) values (9, 20, 'well-modulated', 41);
insert into Criteria (ID, LabID, Name, MaxScore) values (10, 11, 'logistical', 37);
insert into Criteria (ID, LabID, Name, MaxScore) values (11, 2, '3rd generation', 35);
insert into Criteria (ID, LabID, Name, MaxScore) values (12, 3, 'forecast', 77);
insert into Criteria (ID, LabID, Name, MaxScore) values (13, 29, 'Enhanced', 24);
insert into Criteria (ID, LabID, Name, MaxScore) values (14, 15, 'Fully-configurable', 15);
insert into Criteria (ID, LabID, Name, MaxScore) values (15, 30, 'projection', 99);
insert into Criteria (ID, LabID, Name, MaxScore) values (16, 15, 'Programmable', 55);
insert into Criteria (ID, LabID, Name, MaxScore) values (17, 12, 'forecast', 30);
insert into Criteria (ID, LabID, Name, MaxScore) values (18, 23, 'Object-based', 52);
insert into Criteria (ID, LabID, Name, MaxScore) values (19, 20, 'attitude-oriented', 45);
insert into Criteria (ID, LabID, Name, MaxScore) values (20, 17, 'secondary', 7);
insert into Criteria (ID, LabID, Name, MaxScore) values (21, 2, 'Enterprise-wide', 36);
insert into Criteria (ID, LabID, Name, MaxScore) values (22, 3, 'De-engineered', 10);
insert into Criteria (ID, LabID, Name, MaxScore) values (23, 13, 'Reactive', 14);
insert into Criteria (ID, LabID, Name, MaxScore) values (24, 28, 'Programmable', 50);
insert into Criteria (ID, LabID, Name, MaxScore) values (25, 18, '4th generation', 59);
insert into Criteria (ID, LabID, Name, MaxScore) values (26, 13, 'eco-centric', 4);
insert into Criteria (ID, LabID, Name, MaxScore) values (27, 11, 'internet solution', 31);
insert into Criteria (ID, LabID, Name, MaxScore) values (28, 13, 'analyzer', 99);
insert into Criteria (ID, LabID, Name, MaxScore) values (29, 22, 'utilisation', 41);
insert into Criteria (ID, LabID, Name, MaxScore) values (30, 29, 'Synchronised', 96);
insert into Criteria (ID, LabID, Name, MaxScore) values (31, 15, 'circuit', 51);
insert into Criteria (ID, LabID, Name, MaxScore) values (32, 4, 'Multi-channelled', 24);
insert into Criteria (ID, LabID, Name, MaxScore) values (33, 13, 'Synergistic', 7);
insert into Criteria (ID, LabID, Name, MaxScore) values (34, 21, 'systematic', 32);
insert into Criteria (ID, LabID, Name, MaxScore) values (35, 18, 'uniform', 90);
insert into Criteria (ID, LabID, Name, MaxScore) values (36, 25, 'fault-tolerant', 5);
insert into Criteria (ID, LabID, Name, MaxScore) values (37, 25, 'Team-oriented', 90);
insert into Criteria (ID, LabID, Name, MaxScore) values (38, 23, 'analyzing', 73);
insert into Criteria (ID, LabID, Name, MaxScore) values (39, 27, 'circuit', 2);
insert into Criteria (ID, LabID, Name, MaxScore) values (40, 7, 'open system', 63);
insert into Criteria (ID, LabID, Name, MaxScore) values (41, 14, 'Re-contextualized', 21);
insert into Criteria (ID, LabID, Name, MaxScore) values (42, 11, 'standardization', 25);
insert into Criteria (ID, LabID, Name, MaxScore) values (43, 27, 'discrete', 8);
insert into Criteria (ID, LabID, Name, MaxScore) values (44, 15, 'Open-source', 4);
insert into Criteria (ID, LabID, Name, MaxScore) values (45, 9, 'moratorium', 24);
insert into Criteria (ID, LabID, Name, MaxScore) values (46, 29, '6th generation', 69);
insert into Criteria (ID, LabID, Name, MaxScore) values (47, 15, 'Fully-configurable', 4);
insert into Criteria (ID, LabID, Name, MaxScore) values (48, 20, 'fault-tolerant', 62);
insert into Criteria (ID, LabID, Name, MaxScore) values (49, 1, 'Multi-lateral', 62);
insert into Criteria (ID, LabID, Name, MaxScore) values (50, 2, 'Business-focused', 27);
insert into Criteria (ID, LabID, Name, MaxScore) values (51, 29, 'Balanced', 44);
insert into Criteria (ID, LabID, Name, MaxScore) values (52, 11, 'internet solution', 9);
insert into Criteria (ID, LabID, Name, MaxScore) values (53, 7, 'Devolved', 13);
insert into Criteria (ID, LabID, Name, MaxScore) values (54, 18, 'hierarchy', 30);
insert into Criteria (ID, LabID, Name, MaxScore) values (55, 13, 'explicit', 44);
insert into Criteria (ID, LabID, Name, MaxScore) values (56, 24, 'model', 41);
insert into Criteria (ID, LabID, Name, MaxScore) values (57, 19, 'Cloned', 65);
insert into Criteria (ID, LabID, Name, MaxScore) values (58, 21, 'Implemented', 81);
insert into Criteria (ID, LabID, Name, MaxScore) values (59, 22, 'Balanced', 46);
insert into Criteria (ID, LabID, Name, MaxScore) values (60, 9, 'intranet', 81);
insert into Criteria (ID, LabID, Name, MaxScore) values (61, 1, 'Monitored', 40);
insert into Criteria (ID, LabID, Name, MaxScore) values (62, 20, 'zero defect', 13);
insert into Criteria (ID, LabID, Name, MaxScore) values (63, 28, 'Balanced', 9);
insert into Criteria (ID, LabID, Name, MaxScore) values (64, 18, 'foreground', 97);
insert into Criteria (ID, LabID, Name, MaxScore) values (65, 28, 'open architecture', 90);
insert into Criteria (ID, LabID, Name, MaxScore) values (66, 5, 'zero tolerance', 10);
insert into Criteria (ID, LabID, Name, MaxScore) values (67, 26, 'contingency', 68);
insert into Criteria (ID, LabID, Name, MaxScore) values (68, 20, 'Polarised', 34);
insert into Criteria (ID, LabID, Name, MaxScore) values (69, 13, 'logistical', 61);
insert into Criteria (ID, LabID, Name, MaxScore) values (70, 10, 'eco-centric', 67);
insert into Criteria (ID, LabID, Name, MaxScore) values (71, 23, 'instruction set', 68);
insert into Criteria (ID, LabID, Name, MaxScore) values (72, 6, 'firmware', 56);
insert into Criteria (ID, LabID, Name, MaxScore) values (73, 20, 'hardware', 83);
insert into Criteria (ID, LabID, Name, MaxScore) values (74, 5, 'Multi-tiered', 3);
insert into Criteria (ID, LabID, Name, MaxScore) values (75, 5, 'Cross-group', 71);
insert into Criteria (ID, LabID, Name, MaxScore) values (76, 20, 'definition', 5);
insert into Criteria (ID, LabID, Name, MaxScore) values (77, 3, 'executive', 79);
insert into Criteria (ID, LabID, Name, MaxScore) values (78, 5, 'Cross-group', 45);
insert into Criteria (ID, LabID, Name, MaxScore) values (79, 13, 'high-level', 8);
insert into Criteria (ID, LabID, Name, MaxScore) values (80, 22, 'impactful', 76);
insert into Criteria (ID, LabID, Name, MaxScore) values (81, 23, 'focus group', 7);
insert into Criteria (ID, LabID, Name, MaxScore) values (82, 29, 'Profound', 27);
insert into Criteria (ID, LabID, Name, MaxScore) values (83, 21, 'global', 51);
insert into Criteria (ID, LabID, Name, MaxScore) values (84, 22, 'uniform', 54);
insert into Criteria (ID, LabID, Name, MaxScore) values (85, 1, 'user-facing', 70);
insert into Criteria (ID, LabID, Name, MaxScore) values (86, 22, 'hardware', 19);
insert into Criteria (ID, LabID, Name, MaxScore) values (87, 15, 'methodical', 20);
insert into Criteria (ID, LabID, Name, MaxScore) values (88, 30, 'encoding', 75);
insert into Criteria (ID, LabID, Name, MaxScore) values (89, 16, 'Profound', 81);
insert into Criteria (ID, LabID, Name, MaxScore) values (90, 12, 'Profound', 98);
insert into Criteria (ID, LabID, Name, MaxScore) values (91, 23, 'Re-contextualized', 69);
insert into Criteria (ID, LabID, Name, MaxScore) values (92, 3, 'discrete', 4);
insert into Criteria (ID, LabID, Name, MaxScore) values (93, 27, 'Multi-lateral', 94);
insert into Criteria (ID, LabID, Name, MaxScore) values (94, 9, 'leading edge', 89);
insert into Criteria (ID, LabID, Name, MaxScore) values (95, 13, 'standardization', 77);
insert into Criteria (ID, LabID, Name, MaxScore) values (96, 4, 'exuding', 80);
insert into Criteria (ID, LabID, Name, MaxScore) values (97, 1, 'incremental', 49);
insert into Criteria (ID, LabID, Name, MaxScore) values (98, 18, 'intranet', 38);
insert into Criteria (ID, LabID, Name, MaxScore) values (99, 18, 'grid-enabled', 36);
insert into Criteria (ID, LabID, Name, MaxScore) values (100, 26, 'human-resource', 65);
insert into Criteria (ID, LabID, Name, MaxScore) values (101, 9, 'Focused', 18);
insert into Criteria (ID, LabID, Name, MaxScore) values (102, 4, 'Fundamental', 98);
insert into Criteria (ID, LabID, Name, MaxScore) values (103, 19, 'access', 28);
insert into Criteria (ID, LabID, Name, MaxScore) values (104, 16, 'solution', 47);
insert into Criteria (ID, LabID, Name, MaxScore) values (105, 20, 'Realigned', 3);
insert into Criteria (ID, LabID, Name, MaxScore) values (106, 25, 'Optimized', 42);
insert into Criteria (ID, LabID, Name, MaxScore) values (107, 9, 'Implemented', 5);
insert into Criteria (ID, LabID, Name, MaxScore) values (108, 19, 'encompassing', 17);
insert into Criteria (ID, LabID, Name, MaxScore) values (109, 8, 'website', 89);
insert into Criteria (ID, LabID, Name, MaxScore) values (110, 8, 'content-based', 68);
insert into Criteria (ID, LabID, Name, MaxScore) values (111, 7, 'Operative', 57);
insert into Criteria (ID, LabID, Name, MaxScore) values (112, 7, 'groupware', 49);
insert into Criteria (ID, LabID, Name, MaxScore) values (113, 30, 'maximized', 44);
insert into Criteria (ID, LabID, Name, MaxScore) values (114, 4, 'multi-tasking', 81);
insert into Criteria (ID, LabID, Name, MaxScore) values (115, 11, 'Ameliorated', 28);
insert into Criteria (ID, LabID, Name, MaxScore) values (116, 10, 'dynamic', 27);
insert into Criteria (ID, LabID, Name, MaxScore) values (117, 9, 'dedicated', 41);
insert into Criteria (ID, LabID, Name, MaxScore) values (118, 29, 'software', 74);
insert into Criteria (ID, LabID, Name, MaxScore) values (119, 27, 'system engine', 76);
insert into Criteria (ID, LabID, Name, MaxScore) values (120, 25, 'protocol', 20);
insert into Criteria (ID, LabID, Name, MaxScore) values (121, 17, 'context-sensitive', 17);
insert into Criteria (ID, LabID, Name, MaxScore) values (122, 25, 'Digitized', 78);
insert into Criteria (ID, LabID, Name, MaxScore) values (123, 3, 'encompassing', 50);
insert into Criteria (ID, LabID, Name, MaxScore) values (124, 8, 'background', 83);
insert into Criteria (ID, LabID, Name, MaxScore) values (125, 20, 'radical', 75);
insert into Criteria (ID, LabID, Name, MaxScore) values (126, 3, 'even-keeled', 25);
insert into Criteria (ID, LabID, Name, MaxScore) values (127, 2, 'capability', 93);
insert into Criteria (ID, LabID, Name, MaxScore) values (128, 5, 'Balanced', 60);
insert into Criteria (ID, LabID, Name, MaxScore) values (129, 9, 'asymmetric', 40);
insert into Criteria (ID, LabID, Name, MaxScore) values (130, 18, 'tertiary', 67);
insert into Criteria (ID, LabID, Name, MaxScore) values (131, 11, 'Seamless', 80);
insert into Criteria (ID, LabID, Name, MaxScore) values (132, 20, 'reciprocal', 44);
insert into Criteria (ID, LabID, Name, MaxScore) values (133, 9, 'well-modulated', 81);
insert into Criteria (ID, LabID, Name, MaxScore) values (134, 27, 'access', 9);
insert into Criteria (ID, LabID, Name, MaxScore) values (135, 25, 'conglomeration', 26);
insert into Criteria (ID, LabID, Name, MaxScore) values (136, 16, 'throughput', 97);
insert into Criteria (ID, LabID, Name, MaxScore) values (137, 17, 'didactic', 65);
insert into Criteria (ID, LabID, Name, MaxScore) values (138, 25, 'internet solution', 60);
insert into Criteria (ID, LabID, Name, MaxScore) values (139, 27, 'capacity', 41);
insert into Criteria (ID, LabID, Name, MaxScore) values (140, 17, 'hub', 13);
insert into Criteria (ID, LabID, Name, MaxScore) values (141, 27, 'executive', 81);
insert into Criteria (ID, LabID, Name, MaxScore) values (142, 18, 'next generation', 1);
insert into Criteria (ID, LabID, Name, MaxScore) values (143, 5, 'multi-tasking', 39);
insert into Criteria (ID, LabID, Name, MaxScore) values (144, 20, 'Implemented', 50);
insert into Criteria (ID, LabID, Name, MaxScore) values (145, 27, 'Focused', 67);
insert into Criteria (ID, LabID, Name, MaxScore) values (146, 21, 'homogeneous', 28);
insert into Criteria (ID, LabID, Name, MaxScore) values (147, 20, 'circuit', 12);
insert into Criteria (ID, LabID, Name, MaxScore) values (148, 30, 'attitude', 53);
insert into Criteria (ID, LabID, Name, MaxScore) values (149, 12, 'emulation', 92);
insert into Criteria (ID, LabID, Name, MaxScore) values (150, 28, 'stable', 72);

commit;