insert into Permission (Name) values ('Healings');
insert into Permission (Name) values ('Dahler');
insert into Permission (Name) values ('Baitey');
insert into Permission (Name) values ('Lanphere');
insert into Permission (Name) values ('Arnaez');
insert into Permission (Name) values ('Cumbes');
insert into Permission (Name) values ('Itzak');
insert into Permission (Name) values ('Beardsell');
insert into Permission (Name) values ('Stollhofer');
insert into Permission (Name) values ('Benne');
insert into Permission (Name) values ('De Andreis');
insert into Permission (Name) values ('Kalinke');
insert into Permission (Name) values ('Hargreaves');
insert into Permission (Name) values ('Escot');
insert into Permission (Name) values ('Hoodlass');
insert into Permission (Name) values ('Hegerty');
insert into Permission (Name) values ('Hallowell');
insert into Permission (Name) values ('Crocombe');
insert into Permission (Name) values ('Belford');
insert into Permission (Name) values ('Reach');
insert into Permission (Name) values ('Tonner');
insert into Permission (Name) values ('Kleinpeltz');
insert into Permission (Name) values ('Cotterel');
insert into Permission (Name) values ('de Aguirre');
insert into Permission (Name) values ('de Cullip');
insert into Permission (Name) values ('Domingues');
insert into Permission (Name) values ('Hansberry');
insert into Permission (Name) values ('Latchmore');
insert into Permission (Name) values ('Kimbley');
insert into Permission (Name) values ('Sherry');
