CREATE OR REPLACE PROCEDURE
proc_GradeStudent
(StudentID INTEGER,
LabID INTEGER,
GraderID INTEGER,
Grade INTEGER)
MODIFIES SQL DATA
BEGIN
  DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    BEGIN
      ROLLBACK;
      RESIGNAL;
    END;
  START TRANSACTION;
    INSERT INTO Grade(StudentID, LabID, Grade) VALUES (StudentID, LabID, Grade);
    INSERT INTO Log(GraderID, GradeID, TimeStamp) VALUES (GraderID, LAST_INSERT_ID(), CURRENT_TIMESTAMP);
  COMMIT;
END;
/
