delete from Grade where true;

insert into Grade (StudentID, LabID, Grade) values (1, 1, 40);
insert into Grade (StudentID, LabID, Grade) values (2, 3, 10);
insert into Grade (StudentID, LabID, Grade) values (3, 5, 42);
insert into Grade (StudentID, LabID, Grade) values (4, 7, 76);
insert into Grade (StudentID, LabID, Grade) values (5, 9, 13);
insert into Grade (StudentID, LabID, Grade) values (6, 11, 29);
insert into Grade (StudentID, LabID, Grade) values (7, 13, 63);
insert into Grade (StudentID, LabID, Grade) values (8, 15, 91);
insert into Grade (StudentID, LabID, Grade) values (9, 17, 75);
insert into Grade (StudentID, LabID, Grade) values (10, 19, 72);
insert into Grade (StudentID, LabID, Grade) values (11, 21, 73);
insert into Grade (StudentID, LabID, Grade) values (12, 23, 75);
insert into Grade (StudentID, LabID, Grade) values (13, 25, 41);
insert into Grade (StudentID, LabID, Grade) values (14, 27, 62);
insert into Grade (StudentID, LabID, Grade) values (15, 29, 7);
insert into Grade (StudentID, LabID, Grade) values (16, 2, 68);
insert into Grade (StudentID, LabID, Grade) values (17, 4, 17);
insert into Grade (StudentID, LabID, Grade) values (18, 6, 33);
insert into Grade (StudentID, LabID, Grade) values (19, 8, 56);
insert into Grade (StudentID, LabID, Grade) values (20, 10, 48);
insert into Grade (StudentID, LabID, Grade) values (21, 12, 91);
insert into Grade (StudentID, LabID, Grade) values (22, 14, 100);
insert into Grade (StudentID, LabID, Grade) values (23, 16, 74);
insert into Grade (StudentID, LabID, Grade) values (24, 18, 29);
insert into Grade (StudentID, LabID, Grade) values (25, 20, 53);
insert into Grade (StudentID, LabID, Grade) values (26, 22, 99);
insert into Grade (StudentID, LabID, Grade) values (27, 24, 9);
insert into Grade (StudentID, LabID, Grade) values (28, 26, 68);
insert into Grade (StudentID, LabID, Grade) values (29, 28, 57);
insert into Grade (StudentID, LabID, Grade) values (30, 30, 15);

commit;
